name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: make unit-tests
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.txt
      - name: Setup Kubernetes cluster (KIND)
        uses: engineerd/setup-kind@v0.5.0
      - name: Test connection to Kubernetes cluster
        run: |
          kubectl cluster-info
      - name: Run integration tests
        run: make integration-tests
        env:
          KUBECONFIG: /home/runner/.kube/config
      - name: Release snapshot
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v1.5.0
          args: release --snapshot --skip-publish --rm-dist
