name: release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Unshallow # This step is required for the changelog to work correctly
        run: git fetch --prune --unshallow
      - name: Run unit tests
        run: make test
      - name: Run integration tests
        run: make integration-tests
      - name: Release
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
