name: release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run unit tests
        run: make unit-tests
      - name: Setup Kubernetes cluster (KIND)
        uses: engineerd/setup-kind@v0.5.0
      - name: Test connection to Kubernetes cluster
        run: |
          kubectl cluster-info
      - name: Run integration tests
        run: make integration-tests
        env:
          KUBECONFIG: /home/runner/.kube/config
      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.148.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update new version for plugin 'kubectl-who-can' in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.38
